spring.application.name=InventoryManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=Priyanshi@123
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080